# Generated by Django 5.0.7 on 2024-10-16 22:42

import app.bot_ai.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ai', '0001_initial'),
        ('users', '0003_delete_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediasForIATrainig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=app.bot_ai.models.catalog_media_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companymodel')),
            ],
        ),
    ]
