# Generated by Django 5.0.7 on 2024-11-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ai', '0002_mediasforiatrainig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('font_family', models.CharField(blank=True, max_length=255, null=True)),
                ('tone_of_voice', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=24, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BrandColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.branddetails')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('catalog_size', models.CharField(blank=True, max_length=50, null=True)),
                ('product_update_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.companydata')),
            ],
        ),
        migrations.AddField(
            model_name='branddetails',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.companydata'),
        ),
        migrations.CreateModel(
            name='AnalyticsPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.companydata')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.companydata')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.companydata')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=255, null=True)),
                ('account_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.accountsettings')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_integration', models.CharField(blank=True, max_length=255, null=True)),
                ('erp_integration', models.CharField(blank=True, max_length=255, null=True)),
                ('data_transfer_protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.companydata')),
            ],
        ),
        migrations.CreateModel(
            name='MetricsOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('analytics_preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.analyticspreferences')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('catalog_preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.catalogpreferences')),
            ],
        ),
        migrations.CreateModel(
            name='SupportPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_hours_start_time', models.TimeField(blank=True, null=True)),
                ('support_hours_end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.companydata')),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('SKU', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('technical_specifications', models.TextField(blank=True, null=True)),
                ('warranty_information', models.TextField(blank=True, null=True)),
                ('usage_instructions', models.TextField(blank=True, null=True)),
                ('troubleshooting_guides', models.TextField(blank=True, null=True)),
                ('safety_information', models.TextField(blank=True, null=True)),
                ('product_manual_url', models.URLField(blank=True, max_length=500, null=True)),
                ('promotional_info', models.TextField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('sample_reviews', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.clientdata')),
                ('related_products', models.ManyToManyField(blank=True, to='bot_ai.productdata')),
                ('images', models.ManyToManyField(blank=True, to='bot_ai.productimage')),
                ('tags', models.ManyToManyField(blank=True, to='bot_ai.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TroubleshootingPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('support_preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_ai.supportpreferences')),
            ],
        ),
    ]
