# Generated by Django 5.0.7 on 2024-11-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ai', '0003_branddetails_clientdata_companydata_productimage_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
