# Generated by Django 5.0.7 on 2024-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ai', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
