# Generated by Django 5.0.7 on 2024-11-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ai', '0005_alter_productdata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
