# Generated by Django 5.0.7 on 2024-11-08 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ai', '0006_alter_clientdata_cell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_ai.companydata'),
        ),
    ]
